from xhtml2pdf import pisa
from io import BytesIO
import base64
from wordcloud import WordCloud
import matplotlib.pyplot as plt

def generate_pdf_from_html(html_content: str) -> bytes:
    """
    Convert HTML content to PDF bytes.
    """
    result_file = BytesIO()
    pisa_status = pisa.CreatePDF(
        html_content,
        dest=result_file,
        encoding='utf-8'
    )
    if pisa_status.err:
        return None
    return result_file.getvalue()

def create_wordcloud_image(keywords: dict) -> str:
    """
    Generate a word cloud image and return it as a base64 string.
    keywords: dict of {keyword: frequency}
    """
    if not keywords:
        return ""

    # Generate WordCloud
    wc = WordCloud(
        font_path='malgun.ttf', # Windows default; use a font available on system
        width=800, 
        height=400,
        background_color='white'
    ).generate_from_frequencies(keywords)

    # Save to BytesIO
    img = BytesIO()
    wc.to_image().save(img, format='PNG')
    img.seek(0)
    
    # Encode to Base64
    base64_str = base64.b64encode(img.read()).decode('utf-8')
    return f"data:image/png;base64,{base64_str}"

def create_report_html(title: str, summary: str, viz_image: str, items: list) -> str:
    """
    Create a Vercel-styled HTML report.
    """
    item_rows = ""
    for item in items:
        item_rows += f"""
        <div class="card">
            <h3>{item['keyword']} <span class="badge">{item['source']}</span></h3>
            <p class="date">{item['date']}</p>
            <p>{item['summary']}</p>
        </div>
        """

    viz_html = ""
    if viz_image:
        viz_html = f"""
        <div class="section">
            <h2>Trend Visualization</h2>
            <img src="{viz_image}" style="width: 100%; max-width: 800px; border-radius: 8px; border: 1px solid #eaeaea;" />
        </div>
        """

    return f"""
    <html>
    <head>
        <style>
            @page {{
                size: A4;
                margin: 2cm;
                @frame footer_frame {{           /* Static Frame */
                    -pdf-frame-content: footer_content;
                    bottom: 1cm;
                    margin-left: 1cm;
                    margin-right: 1cm;
                    height: 1cm;
                }}
            }}
            body {{
                font-family: 'Helvetica', sans-serif;
                color: #333;
                line-height: 1.6;
            }}
            h1 {{
                font-size: 24px;
                font-weight: 700;
                margin-bottom: 10px;
                color: #000;
            }}
            h2 {{
                font-size: 18px;
                font-weight: 600;
                margin-top: 20px;
                margin-bottom: 15px;
                border-bottom: 1px solid #eaeaea;
                padding-bottom: 10px;
            }}
            .card {{
                border: 1px solid #eaeaea;
                border-radius: 8px;
                padding: 15px;
                margin-bottom: 15px;
                background-color: #fafafa;
            }}
            .card h3 {{
                font-size: 16px;
                margin: 0 0 5px 0;
            }}
            .badge {{
                font-size: 10px;
                background-color: #000;
                color: #fff;
                padding: 2px 6px;
                border-radius: 4px;
                vertical-align: middle;
            }}
            .date {{
                font-size: 10px;
                color: #666;
                margin-bottom: 10px;
            }}
            .summary-box {{
                background-color: #f7f7f7;
                padding: 20px;
                border-radius: 8px;
                margin-bottom: 30px;
                border: 1px solid #eaeaea;
            }}
            
            #footer_content {{
                text-align: center;
                color: #888;
                font-size: 9pt;
            }}
        </style>
    </head>
    <body>
        <div style="margin-bottom: 30px;">
            <h1>{title}</h1>
            <p style="color: #666;">Generated by TrendTracker</p>
        </div>

        <div class="summary-box">
            <h2>Executive Summary</h2>
            <p>{summary.replace(chr(10), '<br/>')}</p>
        </div>

        {viz_html}

        <div class="section">
            <h2>Detailed Insights</h2>
            {item_rows}
        </div>
        
        <div id="footer_content">
            Page <pdf:pagenumber>
        </div>
    </body>
    </html>
    """
